contents:
  keyring:
    - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
  repositories:
    - https://packages.wolfi.dev/os
  packages:
    - wolfi-baselayout
    - tzdata
    - sonarr
    - catatonit
work-dir: /usr/lib/Sonarr/bin
volumes: [ "/config" ]
accounts:
  groups:
    - groupname: nonroot
      gid: 65532
  users:
    - username: nonroot
      uid: 65532
      gid: 65532
      homedir: ""
      shell: ""
  run-as: nonroot:nonroot
environment:
  PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  SSL_CERT_FILE: /etc/ssl/certs/ca-certificates.crt
  XDG_CONFIG_HOME: /config
  DOTNET_RUNNING_IN_CONTAINER: true
  DOTNET_EnableDiagnostics: 0
  TZ: "Etc/UTC"
  UMASK: "0002"
entrypoint: 
  command:
    catatonit -- Sonarr
cmd: --nobrowser
